services:
  postgres:
    build: .
    container_name: kioscopro_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kioscopro_db
    ports:
      - "5433:5432"
    volumes:
      - kioscopro_pgdata:/var/lib/postgresql/data
    command: postgres -c timezone=UTC

volumes:
  kioscopro_pgdata: