services:
  postgres:
    build: .
    container_name: kioscopro_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRESS_PORT}:5432"
    volumes:
      - kioscopro_pgdata:/var/lib/postgresql/data
    command: postgres -c timezone=UTC

volumes:
  kioscopro_pgdata: